# Generated by Django 5.0.1 on 2024-01-03 13:28

from django.db import migrations

      
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
       migrations.RunSQL("""
                                                  
CREATE SEQUENCE IF NOT EXISTS song_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS person_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS jenre_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS artist_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS playlist_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS album_id_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS cringe_seq
    INCREMENT 1
    start 55
    MINVALUE 0
    MAXVALUE 2147483647
    CACHE 1;
                         
CREATE TABLE "jenre" (
  "jenre_id" int PRIMARY KEY default nextval('jenre_id_seq'),
  "jenre_name" text CHECK(char_length("jenre_name")<=30)
);

CREATE TABLE "artist" (
  "artist_id" int PRIMARY KEY default nextval('artist_id_seq'),
  "nickname" text CHECK(char_length("nickname")<=30)
);

CREATE TABLE "person" (
  "person_id" int PRIMARY KEY default nextval('person_id_seq'),
  "person_nickname" text CHECK(char_length("person_nickname")<=30) UNIQUE,
  "person_email" text CHECK ("person_email" ~* '^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
);

CREATE TABLE "song" (
  "song_id" int PRIMARY KEY default nextval('song_id_seq'),
  "song_name" text CHECK(char_length("song_name")<=30),
  "song_url" text,
  "artist_id" int,
  "jenre_id" int
);

CREATE TABLE "playlist" (
  "playlist_id" int PRIMARY KEY default nextval('playlist_id_seq'),
  "creator_id" int,
  "playlist_name" text CHECK(char_length("playlist_name")<=30),
  "creation_date" timestamp,
  "update_time" timestamp
);

CREATE TABLE "album" (
  "album_id" int PRIMARY KEY default nextval('album_id_seq'),
  "name" text CHECK(char_length("name")<=30),
  "album_creator" int,
  "creation_date" timestamp default now()
);

CREATE TABLE "playlist_songs" (
  "playlist_id" int,
  "song_id" int,
  "id" int PRIMARY KEY default nextval('cringe_seq')
);

CREATE TABLE "album_songs" (
  "album_id" int,
  "song_id" int,
  "id" int PRIMARY KEY default nextval('cringe_seq')               
);

CREATE TABLE "person_favourite_song" (
  "person_id" int,
  "song_id" int,
  "id" int PRIMARY KEY default nextval('cringe_seq')
);

CREATE TABLE "users_password" (
  "id" int PRIMARY KEY default nextval('cringe_seq'),
  "person_id" int ,
  "password" text
);
                  

ALTER TABLE "song" ADD FOREIGN KEY ("artist_id") REFERENCES "artist" ("artist_id") ON DELETE CASCADE;

ALTER TABLE "song" ADD FOREIGN KEY ("jenre_id") REFERENCES "jenre" ("jenre_id") ON DELETE CASCADE;

ALTER TABLE "playlist" ADD FOREIGN KEY ("creator_id") REFERENCES "person" ("person_id") ON DELETE CASCADE;

ALTER TABLE "album" ADD FOREIGN KEY ("album_creator") REFERENCES "artist" ("artist_id") ON DELETE CASCADE;

ALTER TABLE "playlist_songs" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlist" ("playlist_id") ON DELETE CASCADE;

ALTER TABLE "playlist_songs" ADD FOREIGN KEY ("song_id") REFERENCES "song" ("song_id") ON DELETE CASCADE;

ALTER TABLE "album_songs" ADD FOREIGN KEY ("album_id") REFERENCES "album" ("album_id") ON DELETE CASCADE;

ALTER TABLE "album_songs" ADD FOREIGN KEY ("song_id") REFERENCES "song" ("song_id") ON DELETE CASCADE;

ALTER TABLE "person_favourite_song" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id") ON DELETE CASCADE;

ALTER TABLE "person_favourite_song" ADD FOREIGN KEY ("song_id") REFERENCES "song" ("song_id") ON DELETE CASCADE;

ALTER TABLE "users_password" ADD FOREIGN KEY ("person_id") REFERENCES "person" ("person_id") ON DELETE CASCADE;
"""
                         ),
    migrations.RunSQL(
        """ -- ARTISTS INSERTION
INSERT INTO artist (artist_id, nickname) VALUES
      (0, 'ПАПИН ОЛИМПОС'), 
      (1, 'Gorillaz'), 
      (2, 'Rakhim'), 
      (3, 'fem.love'), 
      (4, 'DAVA'), 
      (5, 'ЛСП'), 
      (6, 'CALLMYDD'), 
      (7, 'A4'), 
      (8, 'Серёга'), 
      (9, 'Мейби Бейби'), 
      (10, 'Дора'), 
      (11, 'Magna'), 
      (12, 'MORGENSHTERN'), 
      (13, 'Грибы'), 
      (14, 'Михаил Круг'), 
      (15, 'Ирина Аллегрова'), 
      (16, 'Big Baby Tape'), 
      (17, 'Элджей'), 
      (18, 'GAYAZOV$ BROTHER$'), 
      (19, 'Нурминский'), 
      (20, 'Вирус'), 
      (21, 'Монеточка'), 
      (22, 'Даня Милохин'), 
      (23, 'Макс Корж'), 
      (24, 'FACE'), 
      (25, 'PHARAOH'), 
      (26, 'Михаил Шелег'), 
      (27, 'SLAVA MARLOW');
 -- GENRE INSERTION
INSERT INTO jenre (jenre_id, jenre_name) VALUES
      (0, 'Alternative'), 
      (1, 'Industrial'), 
      (2, 'Metal'), 
      (3, 'Spoken Word'), 
      (4, 'J-Pop'), 
      (5, 'Opera'), 
      (6, 'Instrumental'), 
      (7, 'German Pop'), 
      (8, 'German Folk'), 
      (9, 'Indie Pop'), 
      (10, 'Comedy'), 
      (11, 'Classical'), 
      (12, 'Anime'), 
      (13, 'R&B/Soul'), 
      (14, 'Pop'), 
      (15, 'Progressive'), 
      (16, 'Vocal'), 
      (17, 'Enka'), 
      (18, 'Rock'), 
      (19, 'Karaoke'), 
      (20, 'Dance )'), 
      (21, 'Disney'), 
      (22, 'Soundtrack'), 
      (23, 'Reggae'), 
      (24, 'Country'), 
      (25, 'Kayokyoku'), 
      (26, 'Tejano'), 
      (27, 'Holiday'), 
      (28, 'Post-Disco'), 
      (29, 'K-Pop'), 
      (30, 'Latin'), 
      (31, 'Jazz'), 
      (32, 'Tex-Mex');
 -- SONG INSERTION
INSERT INTO song (song_id,song_name, song_url, artist_id, jenre_id ) VALUES
      (0, 'Вот Так', 'MORGENSHTERN - Вот Так (Right Version) ♂ Gachi Remix by Rat TV.mp3', 12, 19), 
      (1, 'Девочка пай', 'Михаил Круг - Девочка пай Right version gachi remix.mp3', 14, 1), 
      (2, 'Fendi', 'Rakhim - Fendi (Right Version) ♂ Gachi Remix by Rat TV.mp3', 2, 16), 
      (3, 'Ну Где Же Ваши ️fingers️', 'Вирус - Ну Где Же Ваши ♂️fingers♂️ (Right Version) Gachi Remix.mp3', 20, 27), 
      (4, 'Surname', 'Big Baby Tape - Surname Right Version Gachi Remix.mp3', 16, 16), 
      (5, 'Монетка', 'ЛСП - Монетка (Right Version) ♂ Gachi Remix by Rat TV.mp3', 5, 7), 
      (6, 'Юморист', '♂FACE - Юморист (Right Version)♂  Gachi Remix.mp3', 24, 26), 
      (7, 'Gachий Раз', '♂ Монеточка - Gachий Раз ♂ (TRedCat Gachi Remix) [Каждый Раз] Low 1[1].mp3', 21, 8), 
      (8, 'ARISTOCRAT', 'MORGENSHTERN - ARISTOCRAT Right version Gachi remix.mp3', 12, 31), 
      (9, 'Втюрилась', 'Дора - Втюрилась (Right Version) ♂ Gachi Remix by Rat TV.mp3', 10, 26), 
      (10, 'Gachiманка', '♂ Монеточка - Gachiманка ♂ (TRedCat Gachi Remix) [Нимфоманка].mp3', 21, 29), 
      (11, 'Тает Лёд', 'Грибы - Тает Лёд (Right Version) ♂ Gachi Remix by Rat TV.mp3', 13, 21), 
      (12, '2 типа людей', 'Макс Корж - 2 типа людей (Right Version) ♂ Gachi Remix by Rat RV.mp3', 23, 16), 
      (13, 'Говновоз', 'Михаил Шелег - Говновоз (Right Version) ♂ Gachi Remix by Rat TV.mp3', 26, 15), 
      (14, 'Дико тусим', 'Даня Милохин - Дико тусим (Right Version) ♂ Gachi Remix.mp3', 22, 8), 
      (15, 'Пока молодой', 'Мейби Бейби - Пока молодой (Right Version) ♂ Gachi Remix by Rat TV.mp3', 9, 27), 
      (16, 'Camry 35', 'SLAVA MARLOW - Camry 3,5 (gachi remix).mp3', 27, 11), 
      (17, 'ICE', 'MORGENSHTERN - ICE (Right Version) ♂ Gachi Remix prod. by Rat TV.mp3', 12, 19), 
      (18, 'Позвони', 'CALLMYDD - Позвони  (Right version) ♂ Gachi remix.mp3', 6, 30), 
      (19, 'Cristal & МОЁТ', 'MORGENSHTERN - Cristal & МОЁТ (Right Version) ♂ Gachi Remix by Rat TV.mp3', 12, 6), 
      (20, 'Black Guard', 'Нурминский - Black Guard (right Version ♂) Gachi Remix.mp3', 19, 21), 
      (21, 'Feel good inc.', 'Gorillaz - Feel good inc. (Gachi mix) ♂Right Version♂_ by Gachi Fingers.mp3', 1, 16), 
      (22, 'Divide', 'Magna - Divide (Right Version) ♂ Gachi Remix by Rat TV.mp3', 11, 32), 
      (23, 'Злой', 'SLAVA MARLOW - Злой (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 28), 
      (24, 'Тепло', 'Макс Корж - Тепло (Right Version) ♂ Gachi Remix by Rat TV.mp3', 23, 13), 
      (25, 'Нет Проблем', 'SLAVA MARLOW - Нет Проблем  (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 4), 
      (26, 'КЛИП ЗА 10 ЛЯМОВ', 'MORGENSHTERN - КЛИП ЗА 10 ЛЯМОВ (Right Version) ♂ Gachi Remix by Rat TV.mp3', 12, 27), 
      (27, 'Валим', 'Нурминский - Валим (♂Right Version♂) Gachi Remix.mp3', 19, 19), 
      (28, 'По глазам', 'SLAVA MARLOW - По глазам (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 0), 
      (29, 'ДИНОЗАВРИКИ', 'ПАПИН ОЛИМПОС - ДИНОЗАВРИКИ || Туда сюда(gachi remix by TRedCat || Right Version).mp3', 0, 4), 
      (30, 'Зашумел Район', 'Нурминский - Зашумел Район (Right Version♂ Gachi Remix).mp3', 19, 20), 
      (31, 'ЧЕРНЫЙ БУМЕР', 'DAVA - ЧЕРНЫЙ БУМЕР (Right Version) ♂ Gachi Remix by Rat TV.mp3', 4, 9), 
      (32, 'Я СЪЕЛ ДЕДА', 'MORGENSHTERN - Я СЪЕЛ ДЕДА (Right Version) Gachi Remix By Rat TV.mp3', 12, 31), 
      (33, 'ДИКО НАПРИМЕР', '♂PHARAOH - ДИКО, НАПРИМЕР♂ (Right version; Gachi Remix; GachiBass).mp3', 25, 8), 
      (34, 'YUNG HEFNER', 'MORGENSHTERN - YUNG HEFNER (right Version) Gachi Remix.mp3', 12, 13), 
      (35, 'Снова Я Напиваюсь', 'SLAVA MARLOW - Снова Я Напиваюсь (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 24), 
      (36, 'Увезите меня на Дип', 'GAYAZOV$ BROTHER$ - Увезите меня на Дип-хаус (Right Version) ♂ Gachi Remix by Rat TV.mp3', 18, 22), 
      (37, 'Быстро', 'SLAVA MARLOW - Быстро (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 21), 
      (38, 'Gucci', 'Big Baby Tape - Gucci (right version♂) Gachi Remix.mp3', 16, 23), 
      (39, 'Падать в CUM', '♂ Монеточка - Падать в CUM ♂ (TRedCat Gachi Remix) [Падать в грязь].mp3', 21, 23), 
      (40, '1000 минус 7', 'fem.love - 1000 минус 7 (Right version) ♂ Gachi remix.mp3', 3, 17), 
      (41, 'MILF', 'Big Baby Tape - MILF (Right Version) ♂ Gachi Remix by Rat TV.mp3', 16, 30), 
      (42, 'Дуло', 'MORGENSHTERN - Дуло (♂Right version, Gachi remix).mp3', 12, 3), 
      (43, 'Ты горишь как огонь', 'SLAVA MARLOW - Ты горишь как огонь (Right Version) ♂ Gachi Remix by Rat TV.mp3', 27, 28), 
      (44, 'Kids', 'A4 - Kids (Right Version) ♂ Gachi Remix by Rat TV.mp3', 7, 10), 
      (45, 'WATAFUK?!', 'MORGENSHTERN - WATAFUK?! (Right Version) ♂ Gachi Remix by Rat TV.mp3', 12, 21), 
      (46, 'El Problema', 'MORGENSHTERN - El Problema (Right Version) ♂ Gachi Remix [by Rat Tv Gachi].mp3', 12, 22), 
      (47, 'ЧЕТЫРЕ УКРАИНКИ', 'MORGENSHTERN - ЧЕТЫРЕ УКРАИНКИ (Right Version) Gachi Remix By Rat TV.mp3', 12, 22), 
      (48, 'ДОМОФОН  ЧИЧА', 'MORGENSHTERN - ДОМОФОН  ЧИЧА (Right Version) Gachi Remix By Rat TV.mp3', 12, 2), 
      (49, 'Малый повзрослел', 'Макс Корж - Малый повзрослел (Right Version) ♂ Gachi Remix by Rat TV.mp3', 23, 6), 
      (50, 'Hokage', 'Big Baby Tape - Hokage (right Version♂) Gachi Remix.mp3', 16, 4), 
      (51, 'Lollipop', 'Элджей - Lollipop (Right Version) ♂ Gachi Remix by Rat TV.mp3', 17, 3), 
      (52, 'Младший leatherman', 'Ирина Аллегрова- Младший leatherman (Gachi remix) [Младший лейтенант].mp3', 15, 11), 
      (53, 'Чёрный Бумер', 'Серёга - Чёрный Бумер (right version♂) Gachi Remix.mp3', 8, 31), 
      (54, 'Что если бросить тебя', 'Нурминский - Что если бросить тебя (Right Version) ♂ Gachi Remix by Rat TV.mp3', 19, 1);
 -- ALBUM INSERTION
INSERT INTO album (album_id, name, album_creator, creation_date) VALUES
      (0, 'ваще не тутовая карта', 0, '2022-06-13 06:39:14'), 
      (1, 'забавная трапеция', 1, '2018-01-28 10:47:49'), 
      (2, 'ваще не тутовая деревяшка', 2, '2018-06-27 23:14:38'), 
      (3, 'желатиновая деревяшка', 3, '2018-06-28 17:31:36'), 
      (4, 'смешная карта', 4, '2018-10-31 20:57:14'), 
      (5, 'альбомный шипим', 5, '2020-12-11 21:09:20'), 
      (6, 'фриканутая карта', 6, '2022-09-05 15:51:14'), 
      (7, 'смешная трапеция', 7, '2020-07-16 11:30:22'), 
      (8, 'альбомный upuzipu', 8, '2021-10-03 11:01:51'), 
      (9, 'конченная почановая', 9, '2020-11-15 14:33:55'), 
      (10, 'конченная почановая', 10, '2020-08-12 15:20:42'), 
      (11, 'забавная карта', 11, '2019-04-30 22:27:27'), 
      (12, 'фриканутая почановая', 12, '2019-09-30 11:03:18'), 
      (13, 'фриканутая почановая', 12, '2021-06-20 05:41:15'), 
      (14, 'забавная трапеция', 12, '2018-04-28 05:38:16'), 
      (15, 'конченная деревяшка', 12, '2018-04-23 15:09:03'), 
      (16, 'золотой excalibbur', 12, '2020-05-25 13:44:49'), 
      (17, 'смешная трапеция', 12, '2021-10-28 10:00:13'), 
      (18, 'смешная карта', 13, '2020-07-12 10:24:42'), 
      (19, 'забавная карта', 14, '2023-01-14 06:03:32'), 
      (20, 'альбомный стас', 15, '2019-03-11 20:22:09'), 
      (21, 'альбомный excalibbur', 16, '2020-03-18 10:47:08'), 
      (22, 'фриканутая деревяшка', 16, '2022-08-19 09:23:46'), 
      (23, 'конченная деревяшка', 17, '2018-10-19 20:41:39'), 
      (24, 'конченная деревяшка', 18, '2018-03-17 13:10:58'), 
      (25, 'фриканутая почановая', 19, '2020-07-29 05:28:37'), 
      (26, 'фриканутая карта', 19, '2023-01-22 09:04:42'), 
      (27, 'забавная карта', 20, '2019-09-17 23:07:26'), 
      (28, 'смешная почановая', 21, '2018-09-19 06:09:48'), 
      (29, 'фриканутая почановая', 21, '2021-09-30 11:11:55'), 
      (30, 'ваще не тутовая карта', 22, '2019-06-03 08:11:23'), 
      (31, 'фриканутая трапеция', 23, '2019-04-21 04:09:37'), 
      (32, 'конченная трапеция', 23, '2018-08-17 17:35:07'), 
      (33, 'желатиновая почановая', 24, '2019-07-30 23:41:27'), 
      (34, 'ваще не тутовая трапеция', 25, '2019-10-23 21:59:10'), 
      (35, 'фриканутая деревяшка', 26, '2018-12-21 05:30:17'), 
      (36, 'забавная деревяшка', 27, '2019-02-28 20:23:11'), 
      (37, 'конченная деревяшка', 27, '2021-05-06 14:35:51'), 
      (38, 'желатиновая карта', 27, '2019-04-03 18:55:10'), 
      (39, 'фриканутая деревяшка', 27, '2022-10-03 14:26:41');
 -- ALBUM SONGS INSERTION
INSERT INTO album_songs (album_id, song_id) VALUES
      (0, 29), 
      (1, 21), 
      (2, 2), 
      (3, 40), 
      (4, 31), 
      (5, 5), 
      (6, 18), 
      (7, 44), 
      (8, 53), 
      (9, 15), 
      (10, 9), 
      (11, 22), 
      (12, 0), 
      (12, 8), 
      (13, 17), 
      (13, 19), 
      (14, 26), 
      (14, 32), 
      (15, 34), 
      (15, 42), 
      (16, 45), 
      (16, 46), 
      (17, 47), 
      (17, 48), 
      (18, 11), 
      (19, 1), 
      (20, 52), 
      (21, 4), 
      (21, 38), 
      (22, 41), 
      (22, 50), 
      (23, 51), 
      (24, 36), 
      (25, 20), 
      (25, 27), 
      (26, 30), 
      (26, 54), 
      (27, 3), 
      (28, 7), 
      (28, 10), 
      (29, 39), 
      (30, 14), 
      (31, 12), 
      (31, 24), 
      (32, 49), 
      (33, 6), 
      (34, 33), 
      (35, 13), 
      (36, 16), 
      (36, 23), 
      (37, 25), 
      (37, 28), 
      (38, 35), 
      (38, 37), 
      (39, 43);
 -- USER INSERTION
INSERT INTO person (person_id, person_nickname, person_email) VALUES 
      (0, 'Ynypap', 'xVSADho@gmail.com'), 
      (1, 'Khishomixi', 'rWEjYIh@gmail.com'), 
      (2, 'Yshasath', 'RABXuZB@gmail.com'), 
      (3, 'Ylivibi', 'EsHKIAP@gmail.com'), 
      (4, 'Inijehanu', 'iEVXygi@gmail.com'), 
      (5, 'Khithykhezhu', 'kvGhfba@gmail.com'), 
      (6, 'Bujutha', 'tZIlVvh@gmail.com'), 
      (7, 'Kylybu', 'MCjRinL@gmail.com'), 
      (8, 'Irepuzhana', 'vrgakaV@gmail.com'), 
      (9, 'Vyloqa', 'WofaqcI@gmail.com');
 -- USER PASSWORD INSERTION
INSERT INTO users_password (person_id, password) VALUES 
      (0, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (1, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (2, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (3, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (4, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (5, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (6, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (7, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (8, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0'), 
      (9, '09f9a81e41c5f1f2d41fd9a7a2b7ddda9d34da69acd4f9a2ad017334a3e4d0d0');
 -- USER_FAV INSERTION
 INSERT INTO person_favourite_song (person_id, song_id) VALUES 
      (0, 1), 
      (0, 2), 
      (0, 3), 
      (0, 0), 
      (1, 2), 
      (1, 3), 
      (1, 4), 
      (1, 1), 
      (1, 0), 
      (1, 5), 
      (2, 10), 
      (2, 1), 
      (2, 0), 
      (2, 8), 
      (2, 4), 
      (2, 2), 
      (2, 6), 
      (2, 9), 
      (2, 3), 
      (2, 5), 
      (2, 11), 
      (2, 7), 
      (2, 12), 
      (3, 31), 
      (3, 23), 
      (3, 3), 
      (3, 12), 
      (3, 45), 
      (3, 13), 
      (3, 38), 
      (3, 34), 
      (3, 20), 
      (3, 48), 
      (3, 6), 
      (3, 49), 
      (3, 9), 
      (3, 28), 
      (3, 26), 
      (3, 46), 
      (3, 35), 
      (3, 44), 
      (3, 16), 
      (3, 40), 
      (3, 11), 
      (3, 1), 
      (3, 19), 
      (3, 32), 
      (3, 7), 
      (3, 42), 
      (3, 15), 
      (3, 47), 
      (3, 39), 
      (3, 10), 
      (3, 5), 
      (3, 2), 
      (3, 21), 
      (3, 36), 
      (3, 30), 
      (3, 25), 
      (3, 22), 
      (3, 8), 
      (3, 41), 
      (3, 0), 
      (3, 29), 
      (3, 33), 
      (3, 17), 
      (3, 4), 
      (3, 27), 
      (3, 37), 
      (3, 43), 
      (3, 24), 
      (3, 14), 
      (3, 18), 
      (4, 0), 
      (4, 11), 
      (4, 10), 
      (4, 6), 
      (4, 21), 
      (4, 12), 
      (4, 16), 
      (4, 2), 
      (4, 19), 
      (4, 13), 
      (4, 20), 
      (4, 5), 
      (4, 9), 
      (4, 1), 
      (4, 18), 
      (4, 7), 
      (4, 15), 
      (4, 17), 
      (4, 4), 
      (4, 3), 
      (4, 8), 
      (4, 14), 
      (5, 37), 
      (5, 38), 
      (5, 48), 
      (5, 14), 
      (5, 7), 
      (5, 4), 
      (5, 36), 
      (5, 23), 
      (5, 42), 
      (5, 43), 
      (5, 45), 
      (5, 24), 
      (5, 3), 
      (5, 18), 
      (5, 15), 
      (5, 44), 
      (5, 11), 
      (5, 16), 
      (5, 41), 
      (5, 17), 
      (5, 35), 
      (5, 39), 
      (5, 29), 
      (5, 6), 
      (5, 22), 
      (5, 26), 
      (5, 32), 
      (5, 0), 
      (5, 30), 
      (5, 5), 
      (5, 13), 
      (5, 40), 
      (5, 9), 
      (5, 8), 
      (5, 1), 
      (5, 33), 
      (5, 27), 
      (5, 31), 
      (5, 46), 
      (5, 25), 
      (5, 19), 
      (5, 2), 
      (5, 34), 
      (5, 28), 
      (5, 47), 
      (5, 10), 
      (5, 20), 
      (5, 12), 
      (5, 21), 
      (6, 2), 
      (6, 1), 
      (6, 0), 
      (7, 15), 
      (7, 24), 
      (7, 52), 
      (7, 41), 
      (7, 6), 
      (7, 19), 
      (7, 11), 
      (7, 7), 
      (7, 54), 
      (7, 43), 
      (7, 44), 
      (7, 35), 
      (7, 27), 
      (7, 31), 
      (7, 1), 
      (7, 53), 
      (7, 30), 
      (7, 8), 
      (7, 2), 
      (7, 46), 
      (7, 14), 
      (7, 25), 
      (7, 22), 
      (7, 18), 
      (7, 4), 
      (7, 21), 
      (7, 42), 
      (7, 0), 
      (7, 28), 
      (7, 10), 
      (7, 37), 
      (7, 20), 
      (7, 23), 
      (7, 47), 
      (7, 29), 
      (7, 5), 
      (7, 39), 
      (7, 50), 
      (7, 32), 
      (7, 3), 
      (7, 45), 
      (7, 40), 
      (7, 17), 
      (7, 51), 
      (7, 16), 
      (7, 34), 
      (7, 49), 
      (7, 36), 
      (7, 33), 
      (7, 38), 
      (7, 12), 
      (7, 48), 
      (7, 13), 
      (7, 9), 
      (7, 26), 
      (8, 35), 
      (8, 31), 
      (8, 15), 
      (8, 38), 
      (8, 37), 
      (8, 13), 
      (8, 14), 
      (8, 40), 
      (8, 7), 
      (8, 6), 
      (8, 16), 
      (8, 9), 
      (8, 0), 
      (8, 4), 
      (8, 32), 
      (8, 30), 
      (8, 29), 
      (8, 34), 
      (8, 39), 
      (8, 8), 
      (8, 22), 
      (8, 3), 
      (8, 25), 
      (8, 10), 
      (8, 12), 
      (8, 19), 
      (8, 17), 
      (8, 27), 
      (8, 11), 
      (8, 24), 
      (8, 20), 
      (8, 1), 
      (8, 26), 
      (8, 33), 
      (8, 18), 
      (8, 28), 
      (8, 2), 
      (8, 23), 
      (8, 21), 
      (8, 5), 
      (8, 36), 
      (9, 0), 
      (9, 9), 
      (9, 7), 
      (9, 22), 
      (9, 19), 
      (9, 3), 
      (9, 12), 
      (9, 11), 
      (9, 6), 
      (9, 2), 
      (9, 1), 
      (9, 4), 
      (9, 18), 
      (9, 8), 
      (9, 14), 
      (9, 10), 
      (9, 20), 
      (9, 16), 
      (9, 21), 
      (9, 15), 
      (9, 13), 
      (9, 17), 
      (9, 23), 
      (9, 5);
 -- PLAYLIST INSERTION
INSERT INTO playlist (playlist_id, creator_id, playlist_name, creation_date, update_time) VALUES 
      (0, 2, 'Kitatigaplaylist', '2019-08-17 03:53:22', '2021-09-24 18:18:15'), 
      (1, 4, 'Ydugenplaylist', '2019-08-07 10:46:33', '2022-07-02 13:12:34'), 
      (2, 7, 'Fachypubojplaylist', '2018-08-04 10:23:47', '2022-07-26 07:22:31'), 
      (3, 9, 'Aqejoxplaylist', '2019-04-20 18:26:29', '2022-04-15 04:01:37'), 
      (4, 4, 'Iwuxycufoplaylist', '2018-05-23 20:01:37', '2021-11-19 18:10:06');
 -- PLAYLIST SONGS INSERTION
INSERT INTO playlist_songs (playlist_id, song_id) VALUES 
      (0, 24), 
      (0, 22), 
      (0, 23), 
      (0, 13), 
      (0, 28), 
      (0, 1), 
      (0, 21), 
      (0, 0), 
      (0, 7), 
      (0, 18), 
      (0, 2), 
      (0, 10), 
      (0, 25), 
      (0, 8), 
      (0, 11), 
      (0, 29), 
      (0, 17), 
      (0, 26), 
      (0, 19), 
      (0, 15), 
      (0, 9), 
      (0, 16), 
      (0, 6), 
      (0, 14), 
      (0, 31), 
      (0, 5), 
      (0, 3), 
      (0, 30), 
      (0, 27), 
      (0, 12), 
      (0, 20), 
      (0, 4), 
      (1, 7), 
      (1, 3), 
      (1, 4), 
      (1, 6), 
      (1, 2), 
      (1, 8), 
      (1, 1), 
      (1, 5), 
      (1, 12), 
      (1, 10), 
      (1, 14), 
      (1, 0), 
      (1, 11), 
      (1, 9), 
      (1, 13), 
      (2, 0), 
      (2, 1), 
      (3, 13), 
      (3, 7), 
      (3, 17), 
      (3, 1), 
      (3, 12), 
      (3, 10), 
      (3, 14), 
      (3, 3), 
      (3, 11), 
      (3, 16), 
      (3, 2), 
      (3, 8), 
      (3, 4), 
      (3, 15), 
      (3, 5), 
      (3, 9), 
      (3, 18), 
      (3, 0), 
      (3, 6);
"""
    )

       
    ]
