# Generated by Django 5.0.1 on 2024-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freakify', '0001_init_model'),
    ]

    operations = [
        migrations.RunSQL("""CREATE OR REPLACE PROCEDURE add_user(
username text,
email text,
password text       
)
language plpgsql
    as $$
    begin 
        insert into person (person_nickname, person_email) values(username,email);
        insert into users_password(person_id, password) values (currval('person_id_seq'), password);
    end; $$
"""
)
    ]
