# Generated by Django 5.0.1 on 2024-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freakify', '0002_procedures'),
    ]

    operations = [
        migrations.RunSQL(
            "alter table playlist alter column creation_date set default CURRENT_TIMESTAMP;"
),
migrations.RunSQL(
    "alter table playlist alter column update_time set default CURRENT_TIMESTAMP;"
)
    ]
