# Generated by Django 5.0.1 on 2024-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freakify', '0004_trigger_for_playlist_update'),
    ]

    operations = [
        migrations.RunSQL(
            """ALTER TABLE person_favourite_song ADD UNIQUE (person_id, song_id);
            ALTER TABLE album_songs ADD UNIQUE (album_id, song_id);
        

            """
        )
       
    ]
